spring:
  application:
    name: user-consumer
server:
  port: 8081
eureka:
  client:
    service-url:
      #      defaultZone: http://registrar:7900/eureka/   #  docker环境用这个配置
      defaultZone: http://lisz:666@localhost:7900/eureka/
    healthcheck:
      enabled: true
  instance:
    metadata-map:
      dalao: lisz-hahaha
management:
  endpoints:
    web:
      # Actuator上报
      exposure:
        include: '*'
  endpoint:
    shutdown:
      # 调 Up/Down 状态
      enabled: true
feign:
  circuitbreaker:
    enabled: true